config/routes.rb
GMap::Application.routes.draw do

resources :users do
  resources :locations
  resources :travelogues
  end

match 'auth/:provider/callback', to: 'sessions#create'

match 'auth/failure', to: redirect('/')

match 'signout', to: 'sessions#destroy', as: 'signout'

match 'profile_welcome/:id' , to: 'sessions#show' , as: 'profile_welcome'
  
match 'users/:user_id/locations/:id/hospitals', to: 'locations#hospitals', as: 'hospitals_only'

   root :to => 'sessions#index'

end

app/models/travelogue.rb
class Travelogue < ActiveRecord::Base
  belongs_to :user
  attr_accessible :address, :gmaps, :latitude, :longitude
end

app/controllers/travelogues_controller.rb
class TraveloguesController < ApplicationController
  # GET /travelogues
  # GET /travelogues.json
  def index
    @u=User.find_by_id(params[:user_id]) 
    @travelogue = Travelogue.find(:all, :conditions => ["user_id = ?",@u.id ])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @travelogue }
    end
  end

 
  def show
    
    @user=User.find_by_id(params[:user_id])
    @travelogue = Travelogue.find_by_id(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @travelogue }
    end
  end

  
  def new
   
    @user=User.find_by_id(params[:user_id])
    @travelogue = Travelogue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @travelogue }
    end
  end

  # GET /travelogues/1/edit
  def edit
    @user=User.find_by_id(params[:user_id])
    @travelogue = Travelogue.find_by_id(params[:id])
  end

  # POST /travelogues
  # POST /travelogues.json
  def create
    @user=User.find_by_id(params[:user_id])
    @travelogue = Travelogue.new(params[:travelogue])
    @travelogue.user_id = @user.id
    
    respond_to do |format|
      if @travelogue.save
        format.html { redirect_to user_travelogues_path , notice: 'Travelogue was successfully created.' }
        format.json { render json: @travelogue, status: :created, location: @travelogue }
      else
        format.html { render action: "new" }
        format.json { render json: @travelogue.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def update
    @travelogue = Travelogue.find(params[:id])
      
    respond_to do |format|
      if @travelogue.update_attributes(params[:travelogue])
        format.html { redirect_to user_travelogues_path, notice: 'Travelogue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @travelogue.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user=User.find_by_id(params[:user_id])
    @travelogue = Travelogue.find_by_id(params[:id])
    @travelogue.destroy

    respond_to do |format|
      format.html { redirect_to user_travelogues_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/travelogues_helper.rb
module TraveloguesHelper
end

app/views/travelogues/_form.html.erb
<!--%= form_for([@user,@travelogue]) do |f| %>
  
  <% if @travelogue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@travelogue.errors.count, "error") %> prohibited this travelogue from being saved:</h2>

      <ul>
      <% @travelogue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :gmaps %><br />
    <%= f.check_box :gmaps %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %-->

app/views/travelogues/edit.html.erb
<!-- <h1>Editing travelogue</h1>

<%= render 'form' %>

%= link_to 'Show', @travelogue % |
<%= link_to 'Back', user_travelogues_path %>
 -->

app/views/travelogues/index.html.erb
<!-- <h1>Listing travelogues</h1>

<table>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Gmaps</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @travelogues.each do |travelogue| %>
  <tr>
    <td><%= travelogue.address %></td>
    <td><%= travelogue.latitude %></td>
    <td><%= travelogue.longitude %></td>
    <td><%= travelogue.gmaps %></td>
    <td><%= travelogue.user %></td>
    <td><%= link_to 'Show', user_travelogue_path(@user , travelogue) %></td>
    
    <td><%= link_to 'Destroy', user_travelogue_path(@user , travelogue), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>





 -->

app/views/travelogues/new.html.erb
<!-- <h1>New travelogue</h1>

<%= render 'form' %>

<%= link_to 'Back', user_travelogues_path%>
 -->

app/views/travelogues/show.html.erb
<!-- <p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @travelogue.address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @travelogue.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @travelogue.longitude %>
</p>

<p>
  <b>Gmaps:</b>
  <%= @travelogue.gmaps %>
</p>

<p>
  <b>User:</b>
  <%= @travelogue.user %>
</p>

<%= link_to 'Edit', edit_user_travelogue_path(@travelogue) %> |  
<%= link_to 'Back', user_travelogues_path %>
 -->