config/routes.rb
GMap::Application.routes.draw do

resources :users do
  resources :locations
  resources :travelogues
  end

match 'auth/:provider/callback', to: 'sessions#create'

match 'auth/failure', to: redirect('/')

match 'signout', to: 'sessions#destroy', as: 'signout'

match 'profile_welcome/:id' , to: 'sessions#show' , as: 'profile_welcome'
  
match 'users/:user_id/locations/:id/hospitals', to: 'locations#hospitals', as: 'hospitals_only'

   root :to => 'sessions#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :user
  


   attr_accessible :address, :gmaps, :latitude, :longitude, :name , :created_at
  
   reverse_geocoded_by :latitude, :longitude
   after_validation :reverse_geocode

	acts_as_gmappable

	def gmaps4rails_address
	   #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
	  address
	end

	def gmaps4rails_infowindow
	
	 "#{name} was spotted in #{address} \n at #{created_at}"
	end
 
	def gmaps4rails_sidebar
	 name   
	end



 
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
      @u=User.find_by_id(params[:user_id]) 
      array_latest_locations = []
      @graph ||= Koala::Facebook::API.new(@u.oauth_token)
      @friends = @graph.get_connections("me","friends").collect{|f| f["id"] }
      @users=User.all
      @users_new = @users.map { |u| u.uid}
      @common_ones = @users_new & @friends # this gives me the common uid of those who are registered in the user table and the freinds of the current user
      
      @common_ones.each do |common_one|
          
        location_s = Location.where("user_id IN (?)",common_one ) 
        @latest = location_s.last
        array_latest_locations << @latest
      
      end

       @locations = Location.find(:all, :conditions => ["user_id = ?",@u.uid ])
        location=@locations.last
        
      if location.nil?
       #redirect_to new_user_location_path(@u.id)
      else
        puts location.name
        array_latest_locations << location
      end
      #raise array_latest_locations.inspect
      @json = array_latest_locations.compact.to_gmaps4rails
    
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @locations }
      end
    end

  # GET /locations/1
  # GET /locations/1.json

 


  def show
      #@location = Location.find(params[:id])
      @user=User.find_by_id(params[:user_id])
      @location = Location.find_by_id(params[:id])
      a = @location.address 
      
 
      @array_rest = Gmaps4rails.places_for_address( a , 'AIzaSyDBgmxkPQH0JRNFvneP7d8vireve1gCC5Y', type = 'restaurant|amusement_park|shopping_mall|campground|bar|museum|night_club|movie_theater|zoo', radius = 1000)
     # @array_amusementpark_camp= Gmaps4rails.places_for_address( a , 'AIzaSyDBgmxkPQH0JRNFvneP7d8vireve1gCC5Y', type = 'restaurant|amusement_park|shopping_mall|campground|bar|museum|night_club|movie_theater|zoo', radius = 1000)
     # @array_shopping = Gmaps4rails.places_for_address( a , 'AIzaSyDBgmxkPQH0JRNFvneP7d8vireve1gCC5Y', type = 'restaurant|amusement_park|shopping_mall|campground|bar|museum|night_club|movie_theater|zoo', radius = 1000)

      @json = @array_rest.to_json
     #@json = array_rest.to_gmaps4rails

      respond_to do |format|
       format.html # show.html.erb
       format.json { render json: @location }
    
      end 
  
  end


  def new
    
    @user=User.find_by_uid(params[:user_id])
    locations = Location.find(:all, :conditions => ["user_id = ?",@user.uid ])

    if locations.blank?
       location_n = Location.create(:address =>"Manhattan,New York,USA" )

    else
      location_n = locations.last
    end
    
    @json = location_n.to_gmaps4rails
    @location = Location.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @user=User.find_by_id(params[:user_id])
    @location = Location.find_by_id(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
      @user=User.find_by_id(params[:user_id])
      @location = Location.new(params[:location])
      @location.user_id = @user.uid
      @location.name = @user.name
      
      respond_to do |format|
        
        if @location.save
            format.html { redirect_to user_locations_path(@user), notice: 'Location was successfully created.' }
            format.json { render json: @location, status: :created, location: @location }
        else
            format.html { render action: "new" }
            format.json { render json: @location.errors, status: :unprocessable_entity }
        end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to user_locations_path, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @user=User.find_by_id(params[:user_id])
    @location = Location.find_by_id(params[:id])
     @location.destroy
    respond_to do |format|
      format.html { redirect_to user_locations_path }
      format.json { head :no_content }
    end
  end

  def restaurants
  
  end


  def  hospitals
      
    @user=User.find_by_id(params[:user_id])
    @location = Location.find_by_id(params[:id])
     
    b = @location.address
      @array_hosp = Gmaps4rails.places_for_address( b , 'AIzaSyDBgmxkPQH0JRNFvneP7d8vireve1gCC5Y', type = 'dentist|health|hospital', radius = 1000)
    # @array_amusementpark_camp= Gmaps4rails.places_for_address( a , 'AIzaSyDBgmxkPQH0JRNFvneP7d8vireve1gCC5Y', type = 'restaurant|amusement_park|shopping_mall|campground|bar|museum|night_club|movie_theater|zoo', radius = 1000)
    # @array_shopping = Gmaps4rails.places_for_address( a , 'AIzaSyDBgmxkPQH0JRNFvneP7d8vireve1gCC5Y', type = 'restaurant|amusement_park|shopping_mall|campground|bar|museum|night_club|movie_theater|zoo', radius = 1000)
     @json = @array_hosp.to_json
    #@json = array_rest.to_gmaps4rails
       
     # respond_to do |format|
     #   format.html 
     #   format.json { render json: @location }
    
     #end 
 end

  def shopping_malls




  end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for([@user,@location]) do |f| %>

  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2> Please check if your location is correct. If correct click create location</h2>
      
    </div>
    <strong><%= link_to "Not the location you were looking for? CLICK HERE", new_user_location_path(@user.uid)%></strong>
  <% end %>

  </br>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :gmaps %>
    <%= f.check_box :gmaps %>
  </div>


 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>



<%= gmaps4rails(@json) %>

<% content_for :scripts do %>
   
    <script type="text/javascript" charset="utf-8">
        var markersArray = [];
        // On click, clear markers, place a new one, update coordinates in the form
        Gmaps.map.callback = function() {
           alert("If creating a location using the map ..Click on the map to make the draggable marker appear")
            google.maps.event.addListener(Gmaps.map.serviceObject, 'click', function(event) {
              clearOverlays();
              placeMarker(event.latLng);
              updateFormLocation(event.latLng);
            });
        };
        // Update form attributes with given coordinates
        function updateFormLocation(latLng) {
           
            
            $('#location_latitude').val(latLng.lat());
            $('#location_longitude').val(latLng.lng());

        }
        // Add a marker with an open infowsindow
        
        function placeMarker(latLng) {
            
            var marker = new google.maps.Marker({
                position: latLng, 
                map: Gmaps.map.serviceObject,
                draggable: true
            });
            markersArray.push(marker);
            // Set and open infowindow
            var infowindow = new google.maps.InfoWindow({
                content: '<div class="popup"><h4>New Location</h4><p>Drag Me To Desired Location</p>'
            });
            infowindow.open(Gmaps.map.serviceObject,marker);
            // Listen to drag & drop
            google.maps.event.addListener(marker, 'dragend', function() {
                updateFormLocation(this.getPosition());
            });
        }
        // Removes the overlays from the map
        function clearOverlays() {
            
          if (markersArray) {
            for (var i = 0; i < markersArray.length; i++ ) {
              markersArray[i].setMap(null);
            }
          }
          markersArray.length = 0;
        }
    </script>
<% end %>

<%= link_to 'Back', user_locations_path %>



<%= link_to 'submit and go back', user_locations_path %>

app/views/locations/hospitals.html.erb
    
<%= gmaps4rails(@json) %>




    <% content_for :scripts do %>
        
        <script type="text/javascript" charset="utf-8">
            
            alert("going in")
            var marker = new google.maps.Marker({map: map, position: point, clickable: true});

            marker.info = new google.maps.InfoWindow({
            content: '<b>Speed:</b> ' + values.inst + ' knots'
            
            });

            google.maps.event.addListener(marker, 'click', function() {
            marker.info.open(map, marker);
            });
            
        </script>
    <% end %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>
<div id="fb-root"></div>
        <script src="http://connect.facebook.net/en_US/all.js"></script>
       <!--  <p>
              <input type="button"
              onclick="sendRequestToOneRecipient(); return false;"
              value="Send Request to One User"
              />
              <input type="text" value="User ID" name="user_id" />
        </p> -->
        
        
              <a href=# id="send_request_button" 
              onclick="sendRequestToManyRecipients(); return false;"> Send Request to Your Facebook Freinds</a>
         

        <script>
              FB.init({
              appId : '266925696752524',
              status : true,
              cookie : true,
              oauth: true
              }); 

              // to send request to many friends use this function
              function sendRequestToManyRecipients() {
              FB.ui({method: 'apprequests',
              message: 'My Great Request',
              }, requestCallback);
              }

              function requestCallback(response) {
              // Handle callback here
              }



                // function sendRequestToOneRecipient() {
                // var user_name = document.getElementsByName("user_name")[0].value;
                // FB.ui({method: 'apprequests',
                // message: 'My Great Request',
                // to: user_name,
                // }, requestCallback);
                // } 
        

        </script>
</body>
</html> 

    <table class="table table-bordered">
      <tr>
        <th>You were Here on/at :</th>
       <th>Address</th>
        <th>Longitude  </th>
        <th>Latitude</th>
       <th>OPTIONS   </th>    

      </tr>

    <% @locations.each do |location| %>
      <tr>
        <td><%= location.created_at%></td>
        <td><%= location.address%></td> 
        <td><%= location.longitude%></td>
        <td><%= location.latitude   %></td>
        
        <td><%= link_to 'Edit', edit_user_location_path(@u , location) %>
        <td><%= link_to 'Destroy', user_location_path(@u , location) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Hangout Places', user_location_path(@u,location) %></td>
      </tr>
    <% end %>
    </table>

    <br />

    
    <%= link_to 'New Location', new_user_location_path(@u.uid) %>
  <br />
     

    <%= gmaps("map_options" => { "type" => "SATELLITE", "center_longitude" => 180, "zoom" => 3, "auto_adjust" => true},"markers" => { "data" => @json , "options" => {"list_container" => "markers_list" }}) %> 

    <html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:fb="https://www.facebook.com/2008/fbml">


<head>
</head>
<body>

        
<h2>WANT TO KNOW WHERE YOUR FREINDS ARE?????..Click to Find out more  </h2>

<ul id="markers_list">  </ul>
<!--%= link_to 'My travelogues', user_travelogues_path(@u.uid) %>
<%= link_to 'new new My travelogues', new_user_travelogue_path(@u.uid) %> -->

app/views/locations/new.html.erb
<h2>ADD A NEW LOCATION</h2>
<h3>Read The Instructions Carefully</h3>
 <ul>
      <p>You can create your Location manually by filling in the address field/ only the LATLONG fields</p>
      <p>If you want to create by entering the Longitude and the Latitude of your current location then check the GMAPS field</p>
      
 </ul>

<%= render 'form' %>
<%= gmaps4rails(@json) %>
<% content_for :scripts do %>
   
    <script type="text/javascript" charset="utf-8">
        var markersArray = [];
        
        Gmaps.map.callback = function() {
           alert("If creating a location using the map ..Click on the map to make the draggable marker appear")
            google.maps.event.addListener(Gmaps.map.serviceObject, 'click', function(event) {
              clearOverlays();
              placeMarker(event.latLng);
              updateFormLocation(event.latLng);
            });
        };
        // Update form attributes with given coordinates
        function updateFormLocation(latLng) {
           $('#location_latitude').val(latLng.lat());
            $('#location_longitude').val(latLng.lng());
        }

        // Add a marker with an open infowsindow
        
        function placeMarker(latLng) {
            
            var marker = new google.maps.Marker({
                position: latLng, 
                map: Gmaps.map.serviceObject,
                draggable: true
            });
            markersArray.push(marker);
            // Set and open infowindow
            var infowindow = new google.maps.InfoWindow({
                content: '<div class="popup"><h4>New Location</h4><p>Drag Me To Desired Location</p>'
            });
            infowindow.open(Gmaps.map.serviceObject,marker);
            // Listen to drag & drop
            google.maps.event.addListener(marker, 'dragend', function() {
                updateFormLocation(this.getPosition());
            });
        }
        // Removes the overlays from the map
        function clearOverlays() {
            
          if (markersArray) {
            for (var i = 0; i < markersArray.length; i++ ) {
              markersArray[i].setMap(null);
            }
          }
          markersArray.length = 0;
        }
    </script>
<% end %>

<%= link_to 'Back', user_locations_path %>

app/views/locations/show.html.erb
<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>Address:</b>
  <%= @location.address %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.longitude %>
</p>

<p>
  <b>Latitude:</b>
  <%= @location.latitude %>
</p>

<h1>Some Hangout places which you can visit in this locality..</h1>
 
 <%= gmaps4rails(@json) %>

<%= link_to 'Back', user_locations_path %>

<% content_for :scripts do %>
    
    <script type="text/javascript" charset="utf-8">
        
        alert("going in")
        var marker = new google.maps.Marker({map: map, position: point, clickable: true});

        marker.info = new google.maps.InfoWindow({
        content: '<b>Speed:</b> ' + values.inst + ' knots'
        
        });

        google.maps.event.addListener(marker, 'click', function() {
        marker.info.open(map, marker);
        });
        

        
       
        
    </script>
<% end %>
</br>
<%= link_to "Hospitals only", hospitals_only_path %>
 